go:
  version: 1.12
  cgo: false
repository:
  path: github.com/timonwong/ding2wechat
build:
  flags: -mod=vendor -a -tags 'netgo static_build'
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - darwin/amd64
    - darwin/386
    - windows/amd64
    - windows/386
    - linux/arm64
